name: Update Onboarding Site
on:
  workflow_dispatch:
  push:
   branches: 
     - main
   
jobs:
  update_onboarding:
    name: Update onboarding
    runs-on: ubuntu-20.04
    steps:
    - name: Setup ssh access
      run: |
        set -x
        mkdir -p ~/.ssh
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.SERVER_PRIVATE_KEY }}"
        ssh-keyscan ${{ secrets.SERVER_HOST }}>> ~/.ssh/known_hosts
        
    - name: Pull new site	
      run: |	
        set -x	
        eval `ssh-agent -s`	
        ssh-add - <<< "${{ secrets.SERVER_PRIVATE_KEY }}"	
        ssh ${{ secrets.JTKARMA_USER }}@${{ secrets.SERVER_HOST }} -C "cd ${{ secrets.SERVER_WEBSITE_PATH }}; git fetch; git stash; git rebase origin/main"
        

    - name: Reload apache
      run: |
        set -x
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.SERVER_PRIVATE_KEY }}"
        ssh ${{ secrets.JTKARMA_USER }}@${{ secrets.SERVER_HOST }} -C "sudo /etc/init.d/apache2 reload"
